# 3W Dataset on Sensory data predicting Well Faults

# Variable information

* JUS = jusante = downstream
* MON = montante = upstream
* CKP = choke de produção = production choke
* CKGL = choke de gas lift = gas lift choke

1. Pressure at the Permanent Downhole Gauge — deep inside the well <strong>(P-PDG)</strong>;
2. Pressure at the Topside Pressure Transducer — at surface level <strong>(P-TPT)</strong>;
3. Temperature at the Topside Pressure Transducer <strong>T-TPT</strong>;
4. Pressure upstream of the Production Choke <strong>P-MON-CKP</strong>;
5. Temperature downstream of the Production Choke <strong>T-JUS-CKP</strong>;
6. Pressure downstream of the Gas Lift Choke <strong>P-JUS-CKGL</strong>;
7. Temperature downstream of the Gas Lift Choke <strong>T-JUS-CKGL</strong>;
8. Gas Lift Flow Rate — volume of gas being injected <strong>QGL</strong>;

### Understanding Basic Terms
An oil well is essentially a pipe going deep underground. Oil and gas are trapped in rock thousands of meters below. The challenge is getting it to the surface in a controlled way.

<hr>
Downhole Gauge (PDG)
A sensor sitting deep inside the well, close to where the oil actually is. It measures pressure at the source. Think of it as taking the pulse of the reservoir itself. "Downhole" just means underground, inside the well bore.

<hr>
Transducer (TPT)
A transducer is just a device that converts a physical property (like pressure or temperature) into an electrical signal you can record. TPT sits at the top of the well, at surface level. "Topside" means above ground. So P-PDG and P-TPT are both measuring pressure, just one is deep underground and one is at the surface.

<hr>
Production Choke (CKP)
Oil and gas coming up the well is under enormous pressure. You can't just let it blast out freely — it would be dangerous and uncontrollable. The production choke is essentially an adjustable valve that restricts the flow, controlling how fast oil comes out. Think of it like a tap. Measuring pressure before (upstream) and after (downstream) the choke tells you how much pressure is being lost across it, which reveals if something is wrong with flow.

<hr>
Gas Lift Choke (CKGL)
Sometimes a well doesn't have enough natural pressure to push oil to the surface on its own. Gas lift solves this by injecting gas down into the well, which lightens the column of fluid and helps push oil up — like blowing air into a straw submerged in water. The gas lift choke controls how much of that injected gas goes in. QGL is literally measuring how much gas is flowing through this choke.

## Importing Libraries 📚

In [1]:
# Import libraries and packages. 
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import pathlib as Path

### Function to process csv files: 
1. Downsample rows to a 10minute window.
2. Display statical information of windows : min, max, mean, std, slope and range.

In [2]:
def process_file(file):
    df = pd.read_csv(f'{file}')
    df["timestamp"] = pd.to_datetime(df["timestamp"])  # Convert the timestamp column to datetime format.
    df = df.set_index("timestamp")
    feature = df.drop(columns="class").resample("1min").mean() # resample to a 1minute interval with a mean operation
    label = df["class"].resample("1min").apply(lambda x : x.mode()[0])
    df = feature.join(label)

    df["T-TPT"] = df["T-TPT"].ffill().bfill() 
    df['P-PDG'] = df['P-PDG'].where(df['P-PDG'] > 0, np.nan) 
    df['P-PDG'] = df['P-PDG'].bfill().ffill()  # ffill and bfill P-PDG after replacing 0 with NaN 
    return df

<strong>Note:</strong>The reason forward filling is done here is that forward fill works correctly when it carries the last valid reading within the same well episode. If it was applied after concatenation, there's a small risk it forward filled across file boundaries — meaning the last temperature reading from one well got carried into the first rows of a completely different well.

In [3]:
def merge_csv(csv_list):
    return pd.concat(csv_list)

In [4]:
# Loop through all folders and group the timestamps by the date

for folder in range(9):
    folder_path = Path.Path(f'../data/{folder}')
    if folder_path.is_dir():
        csv_list = []
        for file in sorted(folder_path.glob('*.csv')):
            if file.is_file():
                try:
                    file = str(file)
                    df = process_file(file)
                    csv_list.append(df)
                except Exception as e:
                    print(f"Error processing folder {file} : {e}")
        csv_file = merge_csv(csv_list)
        output_path = Path.Path(f'../resampled_csv/{folder}')
        output_path.mkdir(parents=True, exist_ok=True)
        csv_file.to_csv(output_path / f'compressed_{folder}.csv')

Warning: ../data/0/WELL-00001_20170201020207.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170201070114.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170201120124.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170201170311.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170201220228.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170202030343.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170202080239.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170218010146.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170218060218.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170218110218.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170218160135.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170218210311.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170219020042.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170219070031.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170219120021.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170219170053.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170219220332.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170421100251.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170422040000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170424180042.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170424230156.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170425040207.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170425090343.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170425140042.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170520190000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170521000000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170521050000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170521100000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170521150000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170521200000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170522010000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170522060000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170522110000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170522160000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170522210000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170523020012.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170523070000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170523120000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170523170000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170523220000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170524030000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170524080000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170524130000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170524180000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170524230000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170525040000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170525090000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170525140000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170525190000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170526000000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170526050000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170526100000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170526150000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170526200000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170527010000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170527060000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170527110000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170527160000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170527210000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170528020000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170528070000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170528120000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170528170000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170528220000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170626100246.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170626150123.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170626200135.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170627010333.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170823050000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170823100000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170823150000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170823200000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170824010000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170824060000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170824110000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170824160000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170824210000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170825020000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170825070000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170825120000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170825170000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170825220000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170826030000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170826080000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170826130000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170826180000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170826230000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170827040000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170827090000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170827140000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170827190000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170828000000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170828050000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00001_20170828100000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20131211230015.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20131212010148.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20131212030000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20131212050000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20131212070005.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20131214160127.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20131214180036.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20131214200030.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170209120022.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170209170152.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170209220033.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170210030033.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170210080407.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170210130152.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170210180033.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170210230203.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170211040225.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170211090129.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170211140152.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170211190129.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170212000141.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170212050225.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170212100203.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170212150407.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170212200429.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170213010322.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170213060225.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170213110344.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170213160107.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170213210214.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170214020118.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170214070141.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170214120056.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170214170044.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170214220322.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170215030259.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170215080056.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170215130214.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170215180118.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170215230129.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170216040141.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170216090118.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170216140152.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170216190214.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170217000107.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170217050451.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170217100355.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170217150248.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170217200225.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170218010237.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170218060225.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170218110022.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170218160214.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170218210134.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170219020033.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170219070129.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170219120152.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170219170203.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170219220214.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170307200031.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170308010103.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170308060042.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170308110124.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170308160353.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170308210218.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170309020218.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170309070218.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170309120156.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170309170218.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170309220207.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170310030146.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170310080518.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170310130321.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170310180103.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170310230042.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170404030000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170404080045.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170404130000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170404180000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170404230000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170405040000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170405090000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170405140000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170405190000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170406000000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170406050000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170406100000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170406150000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170406200000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170611000108.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170611050011.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170611100000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170611150000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170611200000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170612010000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170612060057.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170612110022.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170612160022.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170612210000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170613020022.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170613070011.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170613120000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170613170000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170613220000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170614030000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170614080057.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170614130000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170614180000.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170614230200.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170615040032.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170615090400.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170615140021.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170615190127.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170616000149.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170616050043.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170616100516.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170616150211.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170616200349.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170617010127.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170617060043.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170617110221.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170617160149.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170617220127.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170618020105.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170618070105.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170618120600.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170618170211.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170618220043.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170619030032.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170619080054.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170619130021.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170619180149.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170619230043.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170620040505.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170620090254.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170620140116.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170620190211.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170620230109.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170621030054.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170621080422.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170621130116.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170621180032.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170621230054.csv has no valid P-PDG readings at all
Warning: ../data/0/WELL-00002_20170622040105.csv has no valid P-PDG readings at all

/var/folders/sr/nm6b0csj7vg6g7krm2dk_nm40000gn/T/ipykernel_33740/4070467448.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["timestamp"] = pd.to_datetime(df["timestamp"])  # Convert the timestamp column to datetime format.

Warning: ../data/8/WELL-00019_20170301182317.csv has no valid P-PDG readings at all

In [5]:
class_labels = {
    0: "Normal Operation",
    1: "Abrupt Increase of BSW",
    2: "Incipient Leak in Production Choke",
    3: "Flow Instability",
    4: "Rapid Productivity Loss",
    5: "Quick Restriction in Production Choke",
    6: "Scaling in Production Choke",
    7: "Hydrate in Production Line",
    8: "Hydrate in Service Line",

    101: "Transient - Abrupt Increase of BSW",
    102: "Transient - Incipient Leak in Production Choke",
    103: "Transient - Flow Instability",
    104: "Transient - Rapid Productivity Loss",
    105: "Transient - Quick Restriction in Production Choke",
    106: "Transient - Scaling in Production Choke",
    107: "Transient - Hydrate in Production Line",
    108: "Transient - Hydrate in Service Line",
}

##  Labels information

BSW (class 1) — water and sediment suddenly mixing into the oil flow. Bad for equipment and product quality.
<hr>
Incipient leak (class 2) — a small, developing leak in the production choke valve before it becomes a full rupture.
<hr>
Flow instability (class 3) — the flow oscillates unpredictably instead of being steady. Often caused by gas-liquid slugging.
<hr>
Rapid productivity loss (class 4) — the well suddenly starts producing much less oil, usually due to reservoir or damage issues.
<hr>
Quick restriction in choke (class 5) — something is partially blocking the production choke, reducing flow.
<hr>
Scaling (class 6) — mineral deposits building up inside the choke, slowly narrowing it.
Hydrate in production line (class 7) — ice-like crystals forming in the production pipe and blocking flow.
<hr>
Hydrate in service line (class 8) — same hydrate problem but in the service/gas lift line instead.

In [6]:
class_labels

{0: 'Normal Operation',
 1: 'Abrupt Increase of BSW',
 2: 'Incipient Leak in Production Choke',
 3: 'Flow Instability',
 4: 'Rapid Productivity Loss',
 5: 'Quick Restriction in Production Choke',
 6: 'Scaling in Production Choke',
 7: 'Hydrate in Production Line',
 8: 'Hydrate in Service Line',
 101: 'Transient - Abrupt Increase of BSW',
 102: 'Transient - Incipient Leak in Production Choke',
 103: 'Transient - Flow Instability',
 104: 'Transient - Rapid Productivity Loss',
 105: 'Transient - Quick Restriction in Production Choke',
 106: 'Transient - Scaling in Production Choke',
 107: 'Transient - Hydrate in Production Line',
 108: 'Transient - Hydrate in Service Line'}

## create training and testing dataset 

Slice the data from different classes to create one huge training dataset

In [9]:
class_1["class"].value_counts()

3

In [17]:
class_1['class'].value_counts().to_dict()

{101.0: 87001, 1.0: 48427, 0.0: 13023}

In [90]:
training_data = []
testing_data= []
max_samples = 40000


for i in range(9):
    class_df = pd.read_csv(f'../resampled_csv/{i}/compressed_{i}.csv')
    n = int(min(max_samples, (len(class_df)-(len(class_df) * 0.25)))) # 75% of the data is for train, 25% for test
    training_data.append(class_df[:n])
    testing_data.append(class_df[n:])

df_train = pd.concat(training_data, ignore_index=True)
df_test = pd.concat(testing_data, ignore_index=True)
df_train["timestamp"] = pd.to_datetime(df_train["timestamp"])
df_test["timestamp"] = pd.to_datetime(df_test["timestamp"])

In [91]:
df_train["class"].value_counts()

class
0.0      54335
3.0      40000
5.0      31901
4.0      31107
6.0      26578
107.0    25823
101.0    25502
108.0    16518
106.0    10711
1.0      10551
8.0      10067
105.0     7376
2.0       5755
102.0      960
7.0        793
Name: count, dtype: int64

In [92]:
# Save new dataset as csv file
df_train.to_csv("../training_set1.csv")
df_test.to_csv("../test_set1.csv")

In [93]:
# Load merged datsaset
df = pd.read_csv("../training_set1.csv")

In [94]:
# Convert timestamp column to datetime format
df["timestamp"] = pd.to_datetime(df["timestamp"])

In [95]:
df.drop(columns="Unnamed: 0", inplace=True)

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297977 entries, 0 to 297976
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   timestamp   297977 non-null  datetime64[ns]
 1   P-PDG       232264 non-null  float64
 2   P-TPT       297974 non-null  float64
 3   T-TPT       257977 non-null  float64
 4   P-MON-CKP   297977 non-null  float64
 5   T-JUS-CKP   297974 non-null  float64
 6   P-JUS-CKGL  57986 non-null   float64
 7   T-JUS-CKGL  0 non-null       float64
 8   QGL         61339 non-null   float64
 9   class       297977 non-null  float64
dtypes: datetime64[ns](1), float64(9)
memory usage: 22.7 MB

In [97]:
df

,timestamp,P-PDG,P-TPT,T-TPT,P-MON-CKP,T-JUS-CKP,P-JUS-CKGL,T-JUS-CKGL,QGL,class
0,2017-02-01 02:02:00,NaN,1.008923e+07,119.094542,1.701031e+06,84.399372,1.564153e+06,NaN,0.0,0.0
1,2017-02-01 02:03:00,NaN,1.008299e+07,119.094797,1.583039e+06,84.092421,1.564164e+06,NaN,0.0,0.0
2,2017-02-01 02:04:00,NaN,1.007665e+07,119.095070,1.577072e+06,84.209982,1.564176e+06,NaN,0.0,0.0
3,2017-02-01 02:05:00,NaN,1.007817e+07,119.095345,1.494507e+06,84.056908,1.564188e+06,NaN,0.0,0.0
4,2017-02-01 02:06:00,NaN,1.008317e+07,119.095612,1.651939e+06,84.662507,1.564200e+06,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
297972,2018-05-19 06:59:00,2.796384e+07,1.927456e+07,126.630150,4.053360e+06,102.890227,NaN,NaN,NaN,108.0
297973,2018-05-19 07:00:00,2.796433e+07,1.927519e+07,126.630073,4.053356e+06,102.889350,NaN,NaN,NaN,108.0
297974,2018-05-19 07:01:00,2.796484e+07,1.927588e+07,126.629995,4.053353e+06,102.888463,NaN,NaN,NaN,108.0
297975,2018-05-19 07:02:00,2.796535e+07,1.927655e+07,126.629943,4.053349e+06,102.887570,NaN,NaN,NaN,108.0
297976,2018-05-19 07:03:00,2.796586e+07,1.927722e+07,126.629822,4.053345e+06,102.886663,NaN,NaN,NaN,108.0

In [98]:
 df.describe()

,timestamp,P-PDG,P-TPT,T-TPT,P-MON-CKP,T-JUS-CKP,P-JUS-CKGL,T-JUS-CKGL,QGL,class
count,297977,2.322640e+05,2.979740e+05,257977.000000,2.979770e+05,297974.000000,5.798600e+04,0.0,61339.000000,297977.00000
mean,2017-12-17 15:14:07.985649920,1.929025e+07,1.290733e+07,95.686947,3.820507e+06,74.103983,2.827195e+06,NaN,0.040870,32.89523
min,2013-12-08 23:00:00,1.203599e+02,1.907455e+01,3.056039,1.004756e+01,17.568465,-1.533523e+05,NaN,0.000000,0.00000
25%,2018-04-01 21:21:00,1.529865e+07,9.144970e+06,94.108126,1.147158e+06,57.953730,2.335832e+06,NaN,0.000000,3.00000
50%,2018-04-13 21:43:00,2.142528e+07,1.382505e+07,115.210712,4.002501e+06,71.774826,3.077357e+06,NaN,0.000000,5.00000
75%,2018-05-19 08:01:00,2.624567e+07,1.680578e+07,118.081260,6.053839e+06,82.259305,3.459423e+06,NaN,0.000000,101.00000
max,2018-10-07 08:22:00,4.231799e+07,3.251319e+07,127.740100,1.303611e+07,173.096100,5.263020e+06,NaN,1.428484,108.00000
std,NaN,1.055629e+07,7.153118e+06,35.871188,3.116078e+06,27.581029,1.416828e+06,NaN,0.216731,46.38101

In [99]:
df.isna().sum()

timestamp          0
P-PDG          65713
P-TPT              3
T-TPT          40000
P-MON-CKP          0
T-JUS-CKP          3
P-JUS-CKGL    239991
T-JUS-CKGL    297977
QGL           236638
class              0
dtype: int64

## HANDLING MISSING VALUES DATA👨🏾‍💻

###  Observation 1:
1. T-JUS-CKP (762990) which has no values, That means the temperature sensor simply wasn't installed on any of these wells. There is no data to validate any estimate against, hence the column will be dropped.

2. P-JUS-CKGL (609,594 missing values), Here the NaN means something structurally different from a normal missing value — it means the gas lift was simply switched off at that time. It's not a sensor failure, it's an operational state. Putting the NaN values as 0 will be the next step to go while creating a new column called "gas_lift_active" to show the model the relationship between the 0 values in P-JUS-CKGL and the gas choke being inactive/active.

#### Questions Asked

<strong>Question:</strong>If the QGL was 0 it means the P-JUS-CKGL is 0. or is the other way around? why i asked is because the QGL has more values than the P-JUS-CKGL, so if we want to use QGL & P-JUS-CKGL to create the gas lift active column, it will lead to some being some value (for QGL) and 0 in the P-JUS-CKGL. or should we just use P-JUS-CKGL? if so why that and not QGL.


<strong>Answer: </strong>QGL is the flow rate of gas being injected — how much gas is moving.
P-JUS-CKGL is the pressure measured downstream of the gas lift choke — what pressure that gas creates after passing through.
Physically, the relationship is:

If QGL = 0 (no gas flowing), then P-JUS-CKGL should also be 0 or negligible
But if P-JUS-CKGL has a value, gas must be flowing, so QGL should also have a value

The fact that QGL has more non-NaN values than P-JUS-CKGL suggests the pressure sensor (P-JUS-CKGL) was simply not installed on some wells, while the flow meter (QGL) was. It's a sensor availability issue, not an operational one.

So the hierarchy is:
QGL is the more reliable indicator of gas lift activity because:

* Flow rate is the direct measure of whether gas is actually being injected
* Pressure downstream can sometimes read a residual value even when flow is minimal
* More wells had the QGL meter installed than the pressure sensor

In [100]:
# Remove T-JUS-CKGL 
df = df.drop(columns="T-JUS-CKGL")

In [101]:
# Fill missing values of P-JUS-CKGL & QGL with	0
df["gas_lift_active"] = df["QGL"].notna().astype(int) # if gas QGL (flow rate) has a value, then the gas lift was active

In [102]:
df["QGL"] = df["QGL"].fillna(0) # Fill NaN values with 0
df["P-JUS-CKGL"] = df["P-JUS-CKGL"].fillna(0)

In [103]:
df.isna().sum()

timestamp              0
P-PDG              65713
P-TPT                  3
T-TPT              40000
P-MON-CKP              0
T-JUS-CKP              3
P-JUS-CKGL             0
QGL                    0
class                  0
gas_lift_active        0
dtype: int64

In [104]:
df

,timestamp,P-PDG,P-TPT,T-TPT,P-MON-CKP,T-JUS-CKP,P-JUS-CKGL,QGL,class,gas_lift_active
0,2017-02-01 02:02:00,NaN,1.008923e+07,119.094542,1.701031e+06,84.399372,1.564153e+06,0.0,0.0,1
1,2017-02-01 02:03:00,NaN,1.008299e+07,119.094797,1.583039e+06,84.092421,1.564164e+06,0.0,0.0,1
2,2017-02-01 02:04:00,NaN,1.007665e+07,119.095070,1.577072e+06,84.209982,1.564176e+06,0.0,0.0,1
3,2017-02-01 02:05:00,NaN,1.007817e+07,119.095345,1.494507e+06,84.056908,1.564188e+06,0.0,0.0,1
4,2017-02-01 02:06:00,NaN,1.008317e+07,119.095612,1.651939e+06,84.662507,1.564200e+06,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...
297972,2018-05-19 06:59:00,2.796384e+07,1.927456e+07,126.630150,4.053360e+06,102.890227,0.000000e+00,0.0,108.0,0
297973,2018-05-19 07:00:00,2.796433e+07,1.927519e+07,126.630073,4.053356e+06,102.889350,0.000000e+00,0.0,108.0,0
297974,2018-05-19 07:01:00,2.796484e+07,1.927588e+07,126.629995,4.053353e+06,102.888463,0.000000e+00,0.0,108.0,0
297975,2018-05-19 07:02:00,2.796535e+07,1.927655e+07,126.629943,4.053349e+06,102.887570,0.000000e+00,0.0,108.0,0
297976,2018-05-19 07:03:00,2.796586e+07,1.927722e+07,126.629822,4.053345e+06,102.886663,0.000000e+00,0.0,108.0,0

###  Observation 2:
P-MON-CKP (1557) and T-JUS-CKP (10416) 

P-MON-CKP and T-JUS-CKP measure the oil flow itself, not the choke hardware. The choke is just a valve — it doesn't generate pressure or temperature, it just controls how much fluid passes through. So what you're measuring is the oil/gas mixture's pressure before it hits the choke (P-MON-CKP) and its temperature after passing through (T-JUS-CKP).
If the values are NaN, it doesn't mean the choke wasn't installed — every producing well must have a production choke, otherwise you can't control the flow at all. NaN here most likely means the sensor was faulty, offline, or not logged during that period. It's not an operational state like with gas lift. So these NaN rows should be treated as genuinely missing data — either impute or drop.


Hence, these missing values will be dropped

In [105]:
# Drop NaN rows from P-MON-CKP and T-JUS-CKP
df = df.dropna(subset=["P-MON-CKP", "T-JUS-CKP"])

In [106]:
df

,timestamp,P-PDG,P-TPT,T-TPT,P-MON-CKP,T-JUS-CKP,P-JUS-CKGL,QGL,class,gas_lift_active
0,2017-02-01 02:02:00,NaN,1.008923e+07,119.094542,1.701031e+06,84.399372,1.564153e+06,0.0,0.0,1
1,2017-02-01 02:03:00,NaN,1.008299e+07,119.094797,1.583039e+06,84.092421,1.564164e+06,0.0,0.0,1
2,2017-02-01 02:04:00,NaN,1.007665e+07,119.095070,1.577072e+06,84.209982,1.564176e+06,0.0,0.0,1
3,2017-02-01 02:05:00,NaN,1.007817e+07,119.095345,1.494507e+06,84.056908,1.564188e+06,0.0,0.0,1
4,2017-02-01 02:06:00,NaN,1.008317e+07,119.095612,1.651939e+06,84.662507,1.564200e+06,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...
297972,2018-05-19 06:59:00,2.796384e+07,1.927456e+07,126.630150,4.053360e+06,102.890227,0.000000e+00,0.0,108.0,0
297973,2018-05-19 07:00:00,2.796433e+07,1.927519e+07,126.630073,4.053356e+06,102.889350,0.000000e+00,0.0,108.0,0
297974,2018-05-19 07:01:00,2.796484e+07,1.927588e+07,126.629995,4.053353e+06,102.888463,0.000000e+00,0.0,108.0,0
297975,2018-05-19 07:02:00,2.796535e+07,1.927655e+07,126.629943,4.053349e+06,102.887570,0.000000e+00,0.0,108.0,0
297976,2018-05-19 07:03:00,2.796586e+07,1.927722e+07,126.629822,4.053345e+06,102.886663,0.000000e+00,0.0,108.0,0

###  Observation 3:
The final column T-TPT is the temperature reading in electrical signals of the natural gas. these signals are gotten from the tranducer, which displays also the pressure of the gas. Since, the pressure is being read, it would most likely be a sensor failure. 

In the case where it isn't a sensory failure it can be because the temperature exceeds the calibrated range (too hot or too cold), the sensor might stop sending valid data


The data will be checked for the temperature at the downstream of the Gas Lift Choke (T-JUS-CKP) to check if the temperature was too hot at the time.

In [107]:
temperature_check_hot = df.loc[(df["T-TPT"].isna()) & (df["T-JUS-CKP"] > 100), ["timestamp","T-JUS-CKP"]]

In [108]:
temperature_check_cold = df.loc[(df["T-TPT"].isna()) & (df["T-JUS-CKP"] < 10), ["timestamp","T-JUS-CKP"]]

In [109]:
temperature_check_hot

Empty DataFrame
Columns: [timestamp, T-JUS-CKP]
Index: []

In [110]:
temperature_check_cold

Empty DataFrame
Columns: [timestamp, T-JUS-CKP]
Index: []

In [111]:
df["T-TPT"] = df["T-TPT"].ffill()

/var/folders/sr/nm6b0csj7vg6g7krm2dk_nm40000gn/T/ipykernel_22993/2863484038.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["T-TPT"] = df["T-TPT"].ffill()

In [112]:
df

,timestamp,P-PDG,P-TPT,T-TPT,P-MON-CKP,T-JUS-CKP,P-JUS-CKGL,QGL,class,gas_lift_active
0,2017-02-01 02:02:00,NaN,1.008923e+07,119.094542,1.701031e+06,84.399372,1.564153e+06,0.0,0.0,1
1,2017-02-01 02:03:00,NaN,1.008299e+07,119.094797,1.583039e+06,84.092421,1.564164e+06,0.0,0.0,1
2,2017-02-01 02:04:00,NaN,1.007665e+07,119.095070,1.577072e+06,84.209982,1.564176e+06,0.0,0.0,1
3,2017-02-01 02:05:00,NaN,1.007817e+07,119.095345,1.494507e+06,84.056908,1.564188e+06,0.0,0.0,1
4,2017-02-01 02:06:00,NaN,1.008317e+07,119.095612,1.651939e+06,84.662507,1.564200e+06,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...
297972,2018-05-19 06:59:00,2.796384e+07,1.927456e+07,126.630150,4.053360e+06,102.890227,0.000000e+00,0.0,108.0,0
297973,2018-05-19 07:00:00,2.796433e+07,1.927519e+07,126.630073,4.053356e+06,102.889350,0.000000e+00,0.0,108.0,0
297974,2018-05-19 07:01:00,2.796484e+07,1.927588e+07,126.629995,4.053353e+06,102.888463,0.000000e+00,0.0,108.0,0
297975,2018-05-19 07:02:00,2.796535e+07,1.927655e+07,126.629943,4.053349e+06,102.887570,0.000000e+00,0.0,108.0,0
297976,2018-05-19 07:03:00,2.796586e+07,1.927722e+07,126.629822,4.053345e+06,102.886663,0.000000e+00,0.0,108.0,0

we see that there is no reason to believe out of range theory. it is sensory failure. hence, we either drop the values or forward fill. Forward-fill T-TPT using the last valid reading. This makes physical sense because temperature at the topside transducer changes slowly and gradually — it doesn't jump suddenly. A forward-fill preserves the last known valid state which is a reasonable approximation.

###  Observation 4:
Since P-PDG has just 50 NaN rows, it will be removed.


Notice the P-PDG Column has a lot of zeros (not NaN) and this might be bad. let me explain:


The P-PDG is the downhole gauge, sitting deep inside the well. Unlike surface sensors, it's in an extremely harsh environment — high pressure, high temperature, constant vibration, corrosive fluids. It is by far the most failure-prone sensor in the entire setup because:

It's physically inaccessible — you can't just swap it out without a workover operation which is expensive
The electrical cable running from deep underground to the surface degrades over time
Power supply interruptions to the downhole tool would cause it to read exactly 0, not NaN — because 0 is the default output when the tool loses power or signal

So a reading of 0 while everything else is normal and class = 0 points strongly to one of two things:

Dead sensor — the PDG lost power or the cable failed, defaulting to 0 output. The well kept producing normally, surface sensors kept reading correctly, operators just lost their downhole visibility
Sensor turned off deliberately — sometimes operators disable the downhole gauge for maintenance or calibration while the well stays online



<strong>Solution?</strong>

The columns will be treated as NaN values (replace 0 with NaN), then i will forward fill and backward fill the values. This is more honest than leaving 0 in there — a 0 bar downhole pressure would confuse your model badly since it looks like a dramatic pressure drop when it isn't one. But this would be done in the `process_file()` function, so we wont get a pressure from another class (i.e a fault) which will spoil our data.


I noticed that for a whole class (like class 0) the P-PDG reading was 0. so it cannot ffill or bfill(). Those rows were removed.

In [113]:
df = df.dropna(ignore_index=True)

In [114]:
df.isna().sum()

timestamp          0
P-PDG              0
P-TPT              0
T-TPT              0
P-MON-CKP          0
T-JUS-CKP          0
P-JUS-CKGL         0
QGL                0
class              0
gas_lift_active    0
dtype: int64

In [115]:
df

,timestamp,P-PDG,P-TPT,T-TPT,P-MON-CKP,T-JUS-CKP,P-JUS-CKGL,QGL,class,gas_lift_active
0,2018-09-05 20:44:00,4.202314e+02,1.753406e+02,114.890700,9.664524e+01,66.754500,0.0,0.0,0.0,0
1,2018-09-05 20:45:00,4.202314e+02,1.753406e+02,114.890700,9.664524e+01,66.754500,0.0,0.0,0.0,0
2,2018-09-05 20:46:00,4.202314e+02,1.753406e+02,114.890700,9.664524e+01,66.754500,0.0,0.0,0.0,0
3,2018-09-05 20:47:00,4.202314e+02,1.753406e+02,114.890700,9.664524e+01,66.754500,0.0,0.0,0.0,0
4,2018-09-05 20:48:00,4.202314e+02,1.753406e+02,114.890700,9.664524e+01,66.754500,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...
232259,2018-05-19 06:59:00,2.796384e+07,1.927456e+07,126.630150,4.053360e+06,102.890227,0.0,0.0,108.0,0
232260,2018-05-19 07:00:00,2.796433e+07,1.927519e+07,126.630073,4.053356e+06,102.889350,0.0,0.0,108.0,0
232261,2018-05-19 07:01:00,2.796484e+07,1.927588e+07,126.629995,4.053353e+06,102.888463,0.0,0.0,108.0,0
232262,2018-05-19 07:02:00,2.796535e+07,1.927655e+07,126.629943,4.053349e+06,102.887570,0.0,0.0,108.0,0
232263,2018-05-19 07:03:00,2.796586e+07,1.927722e+07,126.629822,4.053345e+06,102.886663,0.0,0.0,108.0,0

## Feature Engineering

In [116]:
df

,timestamp,P-PDG,P-TPT,T-TPT,P-MON-CKP,T-JUS-CKP,P-JUS-CKGL,QGL,class,gas_lift_active
0,2018-09-05 20:44:00,4.202314e+02,1.753406e+02,114.890700,9.664524e+01,66.754500,0.0,0.0,0.0,0
1,2018-09-05 20:45:00,4.202314e+02,1.753406e+02,114.890700,9.664524e+01,66.754500,0.0,0.0,0.0,0
2,2018-09-05 20:46:00,4.202314e+02,1.753406e+02,114.890700,9.664524e+01,66.754500,0.0,0.0,0.0,0
3,2018-09-05 20:47:00,4.202314e+02,1.753406e+02,114.890700,9.664524e+01,66.754500,0.0,0.0,0.0,0
4,2018-09-05 20:48:00,4.202314e+02,1.753406e+02,114.890700,9.664524e+01,66.754500,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...
232259,2018-05-19 06:59:00,2.796384e+07,1.927456e+07,126.630150,4.053360e+06,102.890227,0.0,0.0,108.0,0
232260,2018-05-19 07:00:00,2.796433e+07,1.927519e+07,126.630073,4.053356e+06,102.889350,0.0,0.0,108.0,0
232261,2018-05-19 07:01:00,2.796484e+07,1.927588e+07,126.629995,4.053353e+06,102.888463,0.0,0.0,108.0,0
232262,2018-05-19 07:02:00,2.796535e+07,1.927655e+07,126.629943,4.053349e+06,102.887570,0.0,0.0,108.0,0
232263,2018-05-19 07:03:00,2.796586e+07,1.927722e+07,126.629822,4.053345e+06,102.886663,0.0,0.0,108.0,0

> The values of pressure and are too large. The pressured is most likely measure in Pa (Pascal).

1 pa = 0.00001 bar.

In [117]:
bar_equivalent = 0.00001   # standard unit

pressure_cols = ['P-PDG', 'P-TPT', 'P-MON-CKP', 'P-JUS-CKGL']

df[pressure_cols] = df[pressure_cols] * bar_equivalent

/var/folders/sr/nm6b0csj7vg6g7krm2dk_nm40000gn/T/ipykernel_22993/3101302959.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[pressure_cols] = df[pressure_cols] * bar_equivalent

In [118]:
# Rearrange columns so class can be the last column to the right
df = df[["timestamp", "P-PDG", "P-TPT", "T-TPT", "P-MON-CKP", "T-JUS-CKP", "P-JUS-CKGL", "QGL", "gas_lift_active", "class"]]

### Extracting Information from timestamp
Month will be extracted from the timestamp column since weather periods happen in paritcular months, which might affect temperature. Hydrate formation (classes 7 and 8) is strongly temperature-dependent — hydrates form more easily in cold months. BSW increases (class 1) can also correlate with seasonal water influx patterns. So month carries real domain signal, not just arbitrary time information.


<strong>Note from Claude:</strong>
month is a cyclical feature. January (1) and December (12) are actually close together seasonally but numerically they're far apart. A model treating them as 1 and 12 on a linear scale gets confused. The standard fix is to encode month as sine and cosine:

In [121]:
df["month"] = df["timestamp"].dt.month

df["month_sin"] = np.sin(2 * np.pi * df["month"] / 12)
df["month_cos"] = np.cos(2 * np.pi * df["month"] / 12)

df = df.drop(columns=["month"])

/var/folders/sr/nm6b0csj7vg6g7krm2dk_nm40000gn/T/ipykernel_22993/2979057628.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["month"] = df["timestamp"].dt.month
/var/folders/sr/nm6b0csj7vg6g7krm2dk_nm40000gn/T/ipykernel_22993/2979057628.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["month_sin"] = np.sin(2 * np.pi * df["month"] / 12)
/var/folders/sr/nm6b0csj7vg6g7krm2dk_nm40000gn/T/ipykernel_22993/2979057628.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["month_cos"] = np.cos(2 * np.pi * df["month"] / 12)

In [142]:
df

,P-PDG,P-TPT,T-TPT,P-MON-CKP,T-JUS-CKP,P-JUS-CKGL,QGL,gas_lift_active,class,month_sin,month_cos
0,0.004202,0.001753,114.890700,0.000966,66.754500,0.0,0.0,0,0.0,-1.0,-1.836970e-16
1,0.004202,0.001753,114.890700,0.000966,66.754500,0.0,0.0,0,0.0,-1.0,-1.836970e-16
2,0.004202,0.001753,114.890700,0.000966,66.754500,0.0,0.0,0,0.0,-1.0,-1.836970e-16
3,0.004202,0.001753,114.890700,0.000966,66.754500,0.0,0.0,0,0.0,-1.0,-1.836970e-16
4,0.004202,0.001753,114.890700,0.000966,66.754500,0.0,0.0,0,0.0,-1.0,-1.836970e-16
...,...,...,...,...,...,...,...,...,...,...,...
232259,279.638378,192.745633,126.630150,40.533603,102.890227,0.0,0.0,0,108.0,0.5,-8.660254e-01
232260,279.643342,192.751937,126.630073,40.533565,102.889350,0.0,0.0,0,108.0,0.5,-8.660254e-01
232261,279.648377,192.758813,126.629995,40.533526,102.888463,0.0,0.0,0,108.0,0.5,-8.660254e-01
232262,279.653463,192.765515,126.629943,40.533486,102.887570,0.0,0.0,0,108.0,0.5,-8.660254e-01
232263,279.658648,192.772158,126.629822,40.533446,102.886663,0.0,0.0,0,108.0,0.5,-8.660254e-01

### Adding rolling window feature
This will be done to get more information on the data like the std, variance, range and mean.

* STD : Tells the model how far the data point is from the mean, a high std means the pressure (for example) spiked from the normal/average pressure. For fault detection this is arguably the most powerful feature. A pressure that is normally std=0.2 suddenly jumping to std=3.0 is a red flag, even before the mean shifts significantly.
* MEAN: This is the average value over the past window. shows the average value over that time period. If this starts drifting lower over successive windows, something is changing in the well.
* VARIENCE : std squared. Carries the same information as std but amplifies larger deviations because of the squaring. A deviation of 2 contributes 4 to variance, a deviation of 5 contributes 25 = 1.14 bar².
* RANGE: Max - Min. Small range value shows there is no sudden change or spike.
* EWN (Exponential weighting): The most recent row gets the most weight. Weight decays exponentially as you go further back. This is very useful for sensor data because it means the most recent reading matters most — which makes physical sense. A pressure reading from 10 minutes ago is less relevant than the reading from 1 minute ago.

In [ ]:
for col in ['P-PDG','P-TPT', 'T-TPT', 'P-MON-CKP', 'T-JUS-CKP', 'P-JUS-CKGL', 'QGL']:
    df[f"{col}_mean"] = df[col].rolling(window=10, min_periods=1).mean()  # Mean column
    df[f"{col}_var"] = df[col].rolling(window=10, min_periods=1).var().fillna(0)  # Varience column
    df[f"{col}_std"] = df[col].rolling(window=10, min_periods=1).std().fillna(0)  # Standard derivation
    df[f"{col}_range"] = df[col].rolling(window=10, min_periods=1).apply(lambda x : max(x) - min(x))  # Range column

for col in ['P-PDG','P-TPT', 'P-MON-CKP', 'P-JUS-CKGL', 'QGL']:
    df[f"{col}_ewm"] = df[col].ewm(span=10).mean()  # EWM for pressure columns

In [122]:
df["class"].value_counts()

class
3.0      40000
5.0      31901
6.0      26578
107.0    25823
101.0    25502
108.0    16518
0.0      14335
106.0    10711
1.0      10551
8.0      10067
105.0     7376
2.0       5755
4.0       5394
102.0      960
7.0        793
Name: count, dtype: int64

# visualisation

In [32]:
 df.to_csv("cleaned_dataset.csv",index_label=False)

Visualisation done in the visualise notebook.

# Training models

In [61]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score, RandomizedSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,precision_score, RocCurveDisplay, f1_score, recall_score, roc_curve, auc
from sklearn.ensemble import HistGradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [123]:
df = df.drop(columns="timestamp")

In [124]:
def preprocessing(df):
    if df.isna().any(axis=None):
        # Remove T-JUS-CKGL 
        df = df.drop(columns=["T-JUS-CKGL","Unnamed: 0"])
        
        # Fill missing values of P-JUS-CKGL & QGL with	0
        df["gas_lift_active"] = df["QGL"].notna().astype(int)
        
        # Fill NaN values with 0
        df["QGL"] = df["QGL"].fillna(0)
        df["P-JUS-CKGL"] = df["P-JUS-CKGL"].fillna(0)
    
        # Drop NaN rows from P-MON-CKP and T-JUS-CKP
        df = df.dropna(subset=["P-MON-CKP", "T-JUS-CKP"])
        
        if df["T-TPT"].isna().any(axis=None):
            df["T-TPT"] = df["T-TPT"].ffill() 

        df = df.dropna(ignore_index=True)
        
        # Convert to bar
        bar_equivalent = 0.00001   # standard unit
        pressure_cols = ['P-PDG', 'P-TPT', 'P-MON-CKP', 'P-JUS-CKGL']
        df[pressure_cols] = df[pressure_cols] * bar_equivalent

        # Rearrange columns so class can be the last column to the right
        df = df[["timestamp", "P-PDG", "P-TPT", "T-TPT", "P-MON-CKP", "T-JUS-CKP", "P-JUS-CKGL", "QGL", "gas_lift_active", "class"]]

        df["month"] = df["timestamp"].dt.month

        df["month_sin"] = np.sin(2 * np.pi * df["month"] / 12)
        df["month_cos"] = np.cos(2 * np.pi * df["month"] / 12)

        df = df.drop(columns=["month"])

        # Extract datetime information and drop column in preparation for fitting model
        df = df.drop(columns="timestamp")
        
        
        if df.isna().any(axis=None):
            print(f"Missing values still detected")
            return df
        else:
            print(f"Dataframe preprocessed successfully")
            return df
    else:
        print(f"No Missing data")
        return df

In [125]:
# Load test data
test_df = pd.read_csv('../test_set1.csv')
test_df["timestamp"] = pd.to_datetime(test_df["timestamp"])
# Pass it through the preprocessing fucntion
test_df_cleaned = preprocessing(test_df)

Dataframe preprocessed successfully

In [126]:
test_df_cleaned.to_csv("./cleaned_dataset_test.csv")

In [127]:
test_df_cleaned["class"].value_counts()

class
5.0      144048
101.0     61173
0.0       42736
3.0       40368
6.0       37973
1.0       37845
105.0     30180
106.0     15151
4.0       10363
107.0      8242
108.0      7456
7.0        1005
102.0        36
2.0          29
8.0          17
Name: count, dtype: int64

Since we already have our train and test dataset separately we would not need train_test_split

In [128]:
# Instantiate Models
clf_1 = RandomForestClassifier(n_estimators=200,class_weight="balanced")
clf_2 = HistGradientBoostingClassifier(class_weight='balanced')

In [129]:
# Split dataset into X and y
X_train = df.drop(columns=["class"])
y_train = df["class"]
X_test = test_df_cleaned.drop(columns=["class"])
y_test = test_df_cleaned["class"]

In [130]:
# Using RandomForest
clf_1.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=200)

In [131]:
clf_1.score(X_test,y_test)

0.4309769090884106

In [132]:
y_preds = clf_1.predict(X_test)

In [133]:
report_dict = classification_report(y_test, y_preds, output_dict=True,)

class_report_1 = pd.DataFrame(report_dict).transpose()
class_report_1.to_csv("../class_report_1.csv")
class_report_1

/opt/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

              precision    recall  f1-score        support
0.0            0.168541  0.284701  0.211736   42736.000000
1.0            0.670955  0.829647  0.741910   37845.000000
2.0            1.000000  0.482759  0.651163      29.000000
3.0            0.374687  0.771651  0.504437   40368.000000
4.0            0.217240  1.000000  0.356939   10363.000000
5.0            0.755660  0.206237  0.324037  144048.000000
6.0            0.000000  0.000000  0.000000   37973.000000
7.0            0.019898  0.085572  0.032288    1005.000000
8.0            0.666667  0.823529  0.736842      17.000000
101.0          0.877125  0.754058  0.810949   61173.000000
102.0          0.000000  0.000000  0.000000      36.000000
105.0          0.197852  0.509576  0.285034   30180.000000
106.0          0.000000  0.000000  0.000000   15151.000000
107.0          0.806831  0.524509  0.635735    8242.000000
108.0          0.999463  0.998391  0.998926    7456.000000
accuracy       0.430977  0.430977  0.430977       0.430977
macro avg      0.450328  0.484709  0.419333  436622.000000
weighted avg   0.532755  0.430977  0.409570  436622.000000

In [134]:
clf_2.fit(X_train,y_train)

HistGradientBoostingClassifier(class_weight='balanced')

In [135]:
clf_2.score(X_test,y_test)

0.4509071920333836

In [136]:
y_preds_2 = clf_2.predict(X_test)

In [137]:
report_dict = classification_report(y_test, y_preds_2, output_dict=True,)

class_report_2 = pd.DataFrame(report_dict).transpose()
class_report_2.to_csv("../class_report_2.csv")
class_report_2

/opt/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

              precision    recall  f1-score        support
0.0            0.204518  0.321579  0.250025   42736.000000
1.0            0.655016  0.872506  0.748278   37845.000000
2.0            1.000000  0.482759  0.651163      29.000000
3.0            0.687304  0.769471  0.726070   40368.000000
4.0            0.215595  1.000000  0.354715   10363.000000
5.0            0.670659  0.227431  0.339674  144048.000000
6.0            0.000000  0.000000  0.000000   37973.000000
7.0            0.019898  0.085572  0.032288    1005.000000
8.0            0.260870  0.705882  0.380952      17.000000
101.0          0.898359  0.704216  0.789528   61173.000000
102.0          0.000000  0.000000  0.000000      36.000000
105.0          0.191707  0.713088  0.302176   30180.000000
106.0          0.000000  0.000000  0.000000   15151.000000
107.0          0.806831  0.524509  0.635735    8242.000000
108.0          0.992369  0.924356  0.957156    7456.000000
accuracy       0.450907  0.450907  0.450907       0.450907
macro avg      0.440208  0.488758  0.411184  436622.000000
weighted avg   0.538129  0.450907  0.436923  436622.000000